[package]
name = "tui-realm-treeview"
version = "1.0.0"
authors = ["Christian Visintin"]
edition = "2018"
categories = ["command-line-utilities"]
description = "Treeview component for tui-realm"
documentation = "https://docs.rs/tui-realm-treeview"
homepage = "https://github.com/veeso/tui-realm-treeview"
include = ["src/**/*", "LICENSE", "README.md", "CHANGELOG.md"]
keywords = ["tui", "terminal"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/veeso/tui-realm-treeview"

[dependencies]
orange-trees = "0.1.0"
#tuirealm = { version = "^1.0.0", default-features = false, features = [ "derive" ]}
tuirealm = { git = "https://github.com/veeso/tui-realm", branch = "new-api", default-features = false, features = [ "derive" ] } 
unicode-width = "0.1.8"

[dev-dependencies]
crossterm = "0.20"
pretty_assertions = "0.7.2"
tui-realm-stdlib = { git = "https://github.com/veeso/tui-realm-stdlib", branch = "1.0.0" } 
#tui-realm-stdlib = "^1.0.0"

[features]
default = [ "with-crossterm" ]
with-crossterm = [ "tuirealm/with-crossterm" ]
with-termion = [ "tuirealm/with-termion" ]

[[example]]
name = "demo"
path = "examples/demo.rs"
